name: release

on:
  push:
    branches:
      - master

jobs:
  build:
    timeout-minutes: 30
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: push-image
        run: |
          export PROJECT_VERSION=$(cat version.txt)
          docker login ${{ secrets.DOCKER_REGISTRY }} -u ${{ secrets.DOCKER_REGISTRY_USER }} -p ${{ secrets.DOCKER_REGISTRY_TOKEN }}
          docker build -t ${{ secrets.DOCKER_REGISTRY }}/${GITHUB_REPOSITORY}:${PROJECT_VERSION} -t ${{ secrets.DOCKER_REGISTRY }}/${GITHUB_REPOSITORY}:latest .
          docker push ${{ secrets.DOCKER_REGISTRY }}/${GITHUB_REPOSITORY}:${PROJECT_VERSION}
          docker push ${{ secrets.DOCKER_REGISTRY }}/${GITHUB_REPOSITORY}:latest

      - name: setup-sonar
        uses: warchant/setup-sonar-scanner@v1

      - name: sonar
        run: |
          sonar-scanner \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.projectName=${PROJECT_NAME} \
            -Dsonar.projectKey=${GITHUB_REPOSITORY//\//:} \
            -Dsonar.projectVersion=${PROJECT_VERSION}
