name: release

on:
  push:
    branches:
      - master

jobs:
  build:
    timeout-minutes: 30
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: push-image
        run: |
          export PROJECT_NAME=$(echo ${GITHUB_REPOSITORY} | cut -d / -f 2)
          export PROJECT_VERSION=$(cat version.txt)
          docker login docker.pkg.github.com -u x-access-token -p ${GITHUB_TOKEN}
          docker build -t docker.pkg.github.com/${GITHUB_REPOSITORY}/${PROJECT_NAME}:${PROJECT_VERSION} -t docker.pkg.github.com/${GITHUB_REPOSITORY}/${PROJECT_NAME}:latest .
          docker push docker.pkg.github.com/${GITHUB_REPOSITORY}/${PROJECT_NAME}:${PROJECT_VERSION}
          docker push docker.pkg.github.com/${GITHUB_REPOSITORY}/${PROJECT_NAME}:latest
