# This configuration is used for the pull request review
name: review

on:
  pull_request:
    # Runs only on pull request creation and on every new commit to the created pull request
    types: [opened, synchronize]

jobs:
  review:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      # Cancels previous run for this branch that have a different commit id (SHA)
      - name: cancel-previous-run
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      # Checkout the git repository
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GPR_TOKEN }}
          fetch-depth: ""

      # Execute some necessary git commands to get more repository informations
      - name: post-checkout
        run: git fetch --prune --unshallow

      # Verify project version is updated
      - name: project-version-check
        id: project_version_check
        uses: avides/actions-project-version-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file-to-check: version.txt

      # Check if documentation reminder comment is already given
      - name: find-documentation-reminder-comment
        uses: peter-evans/find-comment@v1
        id: find_documentation_reminder_comment
        with:
          issue-number: ${{ github.event.number }}
          body-includes: "Confluence/GitHub documentation added or updated?"

      # Add documentation reminder comment if not given
      - name: documentation-reminder-comment
        uses: jungwinter/comment@v1
        id: create
        if: ${{ steps.find_documentation_reminder_comment.outputs.comment-id == 0 }}
        with:
          type: create
          body: "Confluence/GitHub documentation added or updated?"
          issue_number: ${{ github.event.number }}
          token: ${{ secrets.GITHUB_TOKEN }}

      # Build docker image
      - name: build-image
        env:
          PROJECT_VERSION: ${{ steps.project_version_check.outputs.version }}
        run: |
          docker build -t ${{ secrets.DOCKER_REGISTRY }}/${GITHUB_REPOSITORY}:${PROJECT_VERSION} -t ${{ secrets.DOCKER_REGISTRY }}/${GITHUB_REPOSITORY}:latest .

      # Setup the sonar analyse scanner
      - name: setup-sonar
        uses: warchant/setup-sonar-scanner@v3

        # Execute sonar analysis for current branch
      - name: sonar-analyse
        env:
          SONAR_HOST: ${{ secrets.OS_SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.OS_SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export SONAR_ORGANIZATION=$(echo ${GITHUB_REPOSITORY} | cut -d / -f 1)
          mvn sonar:sonar \
            -Dsonar.host.url=${SONAR_HOST} \
            -Dsonar.login=${SONAR_TOKEN} \
            -Dsonar.organization=${SONAR_ORGANIZATION} \
            -Dsonar.projectKey=${GITHUB_REPOSITORY//\//_} \
            -Dsonar.pullrequest.key=${{ github.event.number }} \
            -Dsonar.pullrequest.branch=${{ github.event.pull_request.head.ref }} \
            -Dsonar.pullrequest.github.repository=${GITHUB_REPOSITORY} \
            -Dsonar.scm.revision=${{ github.event.pull_request.head.sha }}
